import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import { SearchForm } from 'components/SearchForm'
import { useEffect, useState } from 'react'
import { Data } from 'types/data'
import { SearchResults } from 'components/SearchResults'

const Home: NextPage = () => {
  const [data, setData] = useState<Data>()

  useEffect(() => {
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=57585d1e9624443028acab0f0647ea14&language=ja-JP&region=JP&include_adult=false&page=1`
    )
      .then((res) => res.json())
      .then((json) => {
        if (json) {
          console.log('fetch(popularity):', json)
          setData(json)
        }
      })
      .catch((error) => {
        console.error(error)
      })
  }, [])

  return (
    <Layout>
      <Head>
        <title>映画検索サイト</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="wrapper my-10">
        <SearchForm />
        <h2 className="text-lg font-bold mb-10 pl-2 border-l-4 border-primary">人気のある作品</h2>
        <SearchResults data={data} />
      </div>
    </Layout>
  )
}

export default Home
